version: '3.8'
services:
    postgres:
        build:
            context: .
            dockerfile: Dockerfile.postgres.dev
        container_name: blog_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - blog_postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
volumes:
    blog_postgres_data:
